version: '3.8'

services:
  cc98-watchdog:
    build: .
    container_name: cc98-watchdog
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      # Proxy settings - allows container to use host proxy
      - https_proxy=http://host.docker.internal:7890
      - http_proxy=http://host.docker.internal:7890
      - all_proxy=socks5://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890
      - HTTP_PROXY=http://host.docker.internal:7890
      - ALL_PROXY=socks5://host.docker.internal:7890
    # Uncomment below to limit resources
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: 256M
